#!/bin/bash

# Script to create missing Android codegen directories
# This fixes the issue where Android clean fails due to missing codegen directories

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Creating missing Android codegen directories..."

# Create codegen directories for native modules that require them
mkdir -p "$PROJECT_ROOT/node_modules/@react-native-async-storage/async-storage/android/build/generated/source/codegen/jni"
mkdir -p "$PROJECT_ROOT/node_modules/react-native-vector-icons/android/build/generated/source/codegen/jni"

# Create placeholder CMakeLists.txt files if they don't exist
if [ ! -f "$PROJECT_ROOT/node_modules/@react-native-async-storage/async-storage/android/build/generated/source/codegen/jni/CMakeLists.txt" ]; then
    echo "# Placeholder CMakeLists.txt - Generated by codegen during build" > "$PROJECT_ROOT/node_modules/@react-native-async-storage/async-storage/android/build/generated/source/codegen/jni/CMakeLists.txt"
fi

if [ ! -f "$PROJECT_ROOT/node_modules/react-native-vector-icons/android/build/generated/source/codegen/jni/CMakeLists.txt" ]; then
    echo "# Placeholder CMakeLists.txt - Generated by codegen during build" > "$PROJECT_ROOT/node_modules/react-native-vector-icons/android/build/generated/source/codegen/jni/CMakeLists.txt"
fi

echo "Done! Codegen directories created."

